main: ${project.code.package}.Main
name: ${project.name}

version: ${project.version}
description: ${project.description}
website: ${project.url}

api-version: 1.18

authors:
  - CarmJos

softdepend:
  - PlaceholderAPI

commands:
  "ParkourCompetition":
    description: "跑酷竞赛的主指令"
    usage: "/ParkourCompetition"
